StudHelper/StudHelper.Web/Controllers/GroupController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using StudHelper.Application.Interfaces.Services;
using StudHelper.Application.ViewModels.Group;
using StudHelper.Web.Utils;

namespace StudHelper.Web.Controllers
{
    [Authorize]
    public class GroupController : Controller
    {
        private const int PageSize = 4;
        private const int MaxPage = 4;
        private readonly IGroupService groupService;

        public GroupController(IGroupService groupService)
        {
            this.groupService = groupService;
        }

        [AllowAnonymous]
        public async Task<IActionResult> Info(int id)
        {
           var model = await this.groupService.GetAsync(id);
            if (model == null)
            {
                return this.NotFound();
            }

            return this.View(model);
        }

        [AllowAnonymous]
        public async Task<IActionResult> List(int page = 1)
        {
            int offset = (page - 1) * PageSize;
            var groupListItems = await this.groupService.GetAllAsync(offset, PageSize);
            int totalSize = await this.groupService.CountAsync();
            var viewModel = new GroupListViewModel()
            {
                Groups = groupListItems,
                Pager = new JW.Pager(totalSize, page, PageSize, MaxPage)
            };

            return this.View(viewModel);
        }

        public IActionResult Create()
        {
            var viewModel = new CreateGroupViewModel();
            return this.View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateGroupViewModel viewModel)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(viewModel);
            }

            viewModel.OwnerId = this.User.GetUserId();
            var addResult = await this.groupService.AddAsync(viewModel);

            if (!addResult.IsSucceeded)
            {
                return this.StatusCode(500);
            }

            return this.RedirectToAction("Info", new { id=viewModel.Id });
        }

        public async Task<IActionResult> Update(int id)
        {
            int userId = this.User.GetUserId();
            var viewModelResult = await this.groupService.GetToUpdateAsync(userId, id);
            if (!viewModelResult.IsSucceeded)
            {
                return this.NotFound();
            }

            return this.View(viewModelResult.Result);
        }

        [HttpPost]
        public async Task<IActionResult> Update(UpdateGroupViewModel viewModel)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(viewModel);
            }

            int userId = this.User.GetUserId();
            var addResult = await this.groupService.UpdateAsync(userId, viewModel);

            if (!addResult.IsSucceeded)
            {
                return this.StatusCode(500);
            }

            return this.RedirectToAction("Info", new { id = viewModel.Id });
        }
    }
}

StudHelper/StudHelper.Web/Controllers/UserController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using StudHelper.Application.Interfaces.Services;

namespace StudHelper.Web.Controllers
{
    public class UserController : Controller
    {
        private readonly IUserService userService;

        public UserController(IUserService userService)
        {
            this.userService = userService;
        }

        public async Task<IActionResult> Profile(int id)
        {
            var model = await this.userService.GetUserAsync(u => u.Id == id);

            if (!model.IsSucceeded)
            {
                return this.StatusCode(500);
            }

            return this.View(model.Result);
        }
    }
}

StudHelper/StudHelper.Web/Views/Shared/_Layout.cshtml
@using StudHelper.Web.Utils;
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - StudHelper.Web</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    </environment>
    
    @await RenderSectionAsync("Styles", false)
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light sticky-top" style="background-color: #e3f2fd;">
        <div class="container">
            <a asp-area="" asp-controller="Group" asp-action="List" class="navbar-brand">
                <img src="~/images/stud-logo.png" width="30" height="30" alt="" class="d-inline-block align-top" />
                Stud Helper
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggler" aria-controls="navbarToggler" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarToggler">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item"><a class="nav-link" asp-area="" asp-controller="Group" asp-action="List">Groups</a></li>
                    <li class="nav-item"><a class="nav-link" asp-area="" asp-controller="Group" asp-action="List">Users</a></li>
                </ul>

                @if (!User.Identity.IsAuthenticated)
                {
                    <form class="form-inline">
                        <div class="btn-group">
                            <a asp-controller="Account" asp-action="SignIn" class="btn btn-outline-success">Sign in</a>
                            <a asp-controller="Account" asp-action="SignUp" class="btn btn-outline-primary">Sign up</a>
                        </div>
                    </form>
                }
                else
                {
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item"><a class="nav-link" asp-area="" asp-controller="User" asp-action="Profile" asp-route-id="@(this.User.GetUserId())">@User.Identity.Name</a></li>
                    </ul>
                }
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - StudHelper.Web</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>